apiVersion: cnat.amankumar.dev/v1alpha1
kind: At
metadata:
  labels:
    app.kubernetes.io/name: at
    app.kubernetes.io/instance: at-sample
    app.kubernetes.io/part-of: k8s-assignment4
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-assignment4
  name: at-sample
spec:
  # TODO(user): Add fields here
